# Generated by Django 3.2.25 on 2024-11-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.floor')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('ERROR', 'Error'), ('MAINTENANCE', 'Maintenance')], default='OFF', max_length=20)),
                ('last_maintained', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hotel.room')),
            ],
            options={
                'unique_together': {('room', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='LightingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.IntegerField(default=100)),
                ('color_temperature', models.IntegerField(default=2700)),
                ('motion_sensor_enabled', models.BooleanField(default=True)),
                ('auto_dim_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_control', to='hotel.roomdevice')),
            ],
        ),
        migrations.CreateModel(
            name='LifeBeingSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('presence_detected', models.BooleanField(default=False)),
                ('motion_level', models.IntegerField(default=0)),
                ('presence_state', models.CharField(blank=True, max_length=20, null=True)),
                ('sensitivity', models.FloatField(blank=True, null=True)),
                ('online_status', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_being_data', to='hotel.room')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IAQSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('noise', models.FloatField(blank=True, null=True)),
                ('illuminance', models.FloatField(blank=True, null=True)),
                ('online_status', models.BooleanField(default=True)),
                ('device_status', models.CharField(default='operational', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaq_data', to='hotel.room')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotel.hotel'),
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('power_usage', models.FloatField()),
                ('duration', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='hotel.roomdevice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumption', to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_auto_adjust', models.BooleanField(default=True)),
                ('lighting_auto_adjust', models.BooleanField(default=True)),
                ('presence_timeout', models.IntegerField(default=15)),
                ('comfort_temperature', models.FloatField(default=24.0)),
                ('energy_saving_temperature', models.FloatField(default=26.0)),
                ('last_presence_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='ACControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=24.0)),
                ('mode', models.CharField(choices=[('COOL', 'Cooling'), ('HEAT', 'Heating'), ('FAN', 'Fan Only'), ('AUTO', 'Automatic'), ('OFF', 'Off')], default='OFF', max_length=20)),
                ('fan_speed', models.IntegerField(default=1)),
                ('humidity_control', models.BooleanField(default=False)),
                ('target_humidity', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ac_control', to='hotel.roomdevice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('hotel', 'number')},
        ),
    ]
