# Generated by Django 3.2.25 on 2024-11-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdevice',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='roomdevice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='roomdevice',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
