# Generated by Django 3.2.25 on 2024-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_roomdevice_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accontrol',
            name='mode',
            field=models.CharField(default='OFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='accontrol',
            name='temperature',
            field=models.FloatField(default=22.0),
        ),
        migrations.AlterField(
            model_name='roomdevice',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
